src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['basic_infos'])]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Groups(['basic_infos'])]
    private ?string $email = null;

    #[ORM\Column]
    #[Groups(['basic_infos'])]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 55)]
    #[Groups(['basic_infos', 'on_creation_infos'])]
    private ?string $name = null;

    #[ORM\Column(length: 55)]
    #[Groups(['basic_infos', 'on_creation_infos'])]
    private ?string $surname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?\DateTimeInterface $birthdate = null;

    // True if first connection has been done, false otherwise
    #[ORM\Column]
    #[Groups(['basic_infos'])]
    private ?bool $first_connection = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?string $address = null;

    #[ORM\Column(length: 5, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?string $zipcode = null;

    #[ORM\Column(length: 128, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?string $city = null;

    #[ORM\Column(length: 10, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?string $phone = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['basic_infos'])]
    private ?int $sport_age = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['basic_infos'])]
    private ?int $token_amount = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: true)]
    #[Groups(['basic_infos'])]
    private ?Civility $civility = null;

    #[ORM\ManyToMany(targetEntity: Level::class, inversedBy: 'users')]
    #[Groups(['basic_infos'])]
    private Collection $level;

    #[ORM\ManyToMany(targetEntity: Planning::class, inversedBy: 'users')]
    private Collection $courses;

    #[ORM\Column(length: 8, nullable: true)]
    #[Groups(['basic_infos'])]
    private ?string $license_serial = null;

    public function __construct()
    {
        $this->level = new ArrayCollection();
        $this->courses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): static
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function isFirstConnection(): ?bool
    {
        return $this->first_connection;
    }

    public function setFirstConnection(bool $first_connection): static
    {
        $this->first_connection = $first_connection;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): static
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getSportAge(): ?int
    {
        return $this->sport_age;
    }

    public function setSportAge(int $sport_age): static
    {
        $this->sport_age = $sport_age;

        return $this;
    }

    public function getTokenAmount(): ?int
    {
        return $this->token_amount;
    }

    public function setTokenAmount(int $token_amount): static
    {
        $this->token_amount = $token_amount;

        return $this;
    }

    public function getCivility(): ?Civility
    {
        return $this->civility;
    }

    public function setCivility(?Civility $civility): static
    {
        $this->civility = $civility;

        return $this;
    }

    /**
     * @return Collection<int, Level>
     */
    public function getLevel(): Collection
    {
        return $this->level;
    }

    public function addLevel(Level $level): static
    {
        if (!$this->level->contains($level)) {
            $this->level->add($level);
        }

        return $this;
    }

    public function removeLevel(Level $level): static
    {
        $this->level->removeElement($level);

        return $this;
    }

    /**
     * @return Collection<int, Planning>
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Planning $course): static
    {
        if (!$this->courses->contains($course)) {
            $this->courses->add($course);
        }

        return $this;
    }

    public function removeCourse(Planning $course): static
    {
        $this->courses->removeElement($course);

        return $this;
    }

    public function getLicenseSerial(): ?string
    {
        return $this->license_serial;
    }

    public function setLicenseSerial(string $license_serial): static
    {
        $this->license_serial = $license_serial;

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array(Roles::ROLE_ADMIN->value, $this->roles);
    }
}

src/Controller/PanelController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use App\Entity\Roles;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use App\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;

#[IsGranted(new Expression("is_authenticated()"))]
class PanelController extends AbstractController
{
    #[Route('/panel', name: 'app_panel')]
    public function index(#[CurrentUser] User $user): Response
    {
        $response = match ($user->getRoles()[0]) {
            Roles::ROLE_ADMIN->value => $this->render('panel/admin.html.twig'),
            Roles::ROLE_TRAINER->value => $this->render('panel/trainer.html.twig'),
            Roles::ROLE_USER->value => $this->render('panel/user.html.twig'),
            default => new Response("Unknown role: " . $user->getRoles()[0], 500),
        };

        if ($user->isFirstConnection()) $response = new RedirectResponse("/premiereConnexion");
        
        return $response;
    }
}

templates/panel/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Hello PanelController!
{% endblock %}

{% block javascripts %}{% endblock %}

{% block body %}
	{%block header %}{% endblock %}

	<div {{ svelte_component("AdminPanel") }}></div>

	{% block footer %}{% endblock %}
{% endblock %}

templates/panel/trainer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PanelController!
{% endblock %}

{% block body %}{% endblock %}

templates/panel/user.html.twig
{% extends 'base.user.html.twig' %}

{% block title %}Panel utilisateur - Raquettes du Miosson
{% endblock %}

{% block body %}
	<div
		class="flex-1 flex flex-col">
		<!-- Espace réservé pour la navbar, si nécessaire -->
		<div class="hidden md:block md:w-64 lg:w-64"></div>

		<!-- Contenu principal -->
		<div class="ml-64 p-4">
			<div class="max-w-5xl mx-auto bg-white shadow rounded-lg p-6">
				<div class="flex flex-nowrap mb-6 justify-between">
					<div>
						<h1 class="text-2xl font-semibold text-gray-800">Bonjour,
							{{ app.user.name }}
							!</h1>
						<p class="text-gray-500 text-sm">Bienvenue sur votre espace personnel.</p>
					</div>
					<div class="order-last flex mt-4 w-auto items-center border-2 p-2 rounded-lg">
						<p class="text-xl font-bold pr-2">{{ app.user.tokenAmount }}</p>
						<img src="images/userPanel/token-bat-coin-svgrepo-com.svg" class="w-10 h-auto">
					</div>
				</div>

				<h2 class="text-xl font-semibold text-gray-800 mb-4">Mes informations</h2>
				<div class="space-y-4">
					<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Nom :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.name }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Prénom :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.surname }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Date d'anniversaire :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.birthdate|date("Y-m-d") }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Adresse mail :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.email }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Numéro de téléphone :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.phone }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Adresse :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.address }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Code postal :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.zipcode }}</div>
						</div>

						<div class="form-group">
							<p class="text-gray-700 text-sm font-bold mb-2">Ville :</p>
							<div class="p-2 bg-gray-100 rounded-md border-2 shadow-sm">{{ app.user.city }}</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block footer %}{% endblock %}